set_var EASYRSA_REQ_COUNTRY    "${CA_COUNTRY}"
set_var EASYRSA_REQ_PROVINCE   "${CA_PROVINCE}"
set_var EASYRSA_REQ_CITY       "${CA_CITY}"
set_var EASYRSA_REQ_ORG        "${CA_ORGANIZATION}"
set_var EASYRSA_REQ_EMAIL      "${CA_EMAIL}"
set_var EASYRSA_REQ_OU         "Community"
set_var EASYRSA_ALGO           "ec"
set_var EASYRSA_DIGEST         "sha512"
